### REGISTER - Auth Service
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "email": "rabbit-test-2@ecom.com",
  "password": "SuperSecurePassword123"
}

### Получение личного профиля (Запрос в Users Service)
GET http://localhost:3002/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNjM5ZjVmZi05ZjkxLTRjMWYtYTRiNC0wNDY4NGQ5MGI0OTQiLCJpYXQiOjE3ODE2MDA1NzQsImV4cCI6MTc4MTYwMTQ3NH0.YxydeWtQ4L4bT6Ob2fJ8svlWbm6-irRRUR1y_Oognis